### ISSUE TITLE
Commands not registered?

### ISSUE THREAD

**Issue by ghost** [ConnectHolland/tactician-scheduler-plugin#5]
Hi,

I am using your plugin. It's great. Exactly the thing I need and very lightweight. 

I don't know, if it is an error or if it is by purpose: Not all serialized commands are inserted into the register file. The cXXXXX files should be in the register file?!

```
-rw-r--r--+ 1 httpd httpd  14K  6. Nov 15:07 ba030de4-848f-11e5-9aff-4b9f234306c3
-rw-r--r--+ 1 httpd httpd  14K  6. Nov 15:07 ba0390d4-848f-11e5-991c-c409c2195d3d
-rw-r--r--+ 1 httpd httpd  179  6. Nov 15:01 cfc32e12-848e-11e5-967f-e34c4e614c26
-rw-r--r--+ 1 httpd httpd  182  6. Nov 15:01 cfc3bfd0-848e-11e5-9911-ead199f82018

a:2:{s:36:"ba030de4-848f-11e5-9aff-4b9f234306c3";i:1446822454;s:36:"ba0390d4-848f-11e5-991c-c409c2195d3d";i:1446883654;}
```

**Comment by RonRademaker** [comment]
Good to hear the plugin helps you!

That sounds like an error. Could you post the contents of the files? If there's sensitive information in there feel free to replace that by XXXXXX or mask it otherwise.

**Comment by ghost** [comment]
I should unserialize() them then? Viewing them in any editor make them look like a binary.

**Comment by RonRademaker** [comment]
I can only think of two situations where this could happen, either the register file didn't update when scheduling or the commands weren't removed from the disk after execution. I thought maybe the timestamp in the files could indicate which is the case.

Best would be of you had some method of reproducing this, perhaps a small script?

**Comment by ghost** [comment]
The Project is not that small, I don't know where this happened. I will look into this. Unserializing them would be a great help. Any idea how I can reproduce the content to see at which situation this happend? CommandName would be enough.

I might change to MongoDB either way. Seems more transparent and reproducable to me.

EDIT:

Here is one of those cXXXX timestamps. The other is unreadable in plain editing mode. Maybe this is the issue? The normal readable file is probably the correct one. And the other had some serialize errors? Any ways, both were not scheduled. 

```
O:62:"Util\Service\Commandbus\Command\XXXXXXXXXXXXCommand":1:{s:84:"\00ConnectHolland\Tactician\SchedulerPlugin\Command\AbstractScheduledCommand\00timestamp";i:1446818471;}
```

Timestamps are as follows:

```
06.11.2015 15:01:11 cfc32e12-848e-11e5-967f-e34c4e614c26
06.11.2015 16:07:34 ba030de4-848f-11e5-9aff-4b9f234306c3
07.11.2015 09:07:34 ba0390d4-848f-11e5-991c-c409c2195d3d
```

Seems like the cXXX command is in the past and not removed from the filesystem. It may be handled, because it is not the register file.

**Comment by RonRademaker** [comment]
Yes, I think something broke when scheduling _(update: or executing)_ because of the serialization. Serialization can be tricky sometimes, maybe there are closures somewhere?

_Update: I don't think the command got executed._

Mongo also serializes, I thinking about a way to reduce the dependency on the serialize function because it makes it hard to see what's happening. I also found that mongo is unable to query serialized data due to null characters. Still I think mongo works a bit better than files. Especially in a distributed environment.

I think your best bet is to implement serialization in your command to make sure the result makes sense. See http://php.net/manual/en/class.serializable.php 

Another option you may want to consider (if you're not doing it already) is add tactician's logger middleware to your commandbus, it may give a bit more insight in what's happening.

**Comment by ghost** [comment]
Ok. I will give MongoDB a try first. Might be visible there were it happend. If the problem still perists, I will look into serializing commands manually. Commands are not using any closures, but some handlers do.

Calling the following will not break serialization?! This is inserted because I can call `$commandbus->handle($command)` directly without setting the timestamp each time a command should be queued.

```
EvaluationCommand extends AbstractScheduled....

public function __construct(Evalution $eval)
{
  $this->setTimestamp(Carbon::now()->modify('+10 second')->getTimestamp());
]
```

Seems to work, but may break serialization? I don't know. This command is essential in the process-logic of my application. I would have noticed if this command isn't executed at all.

I am using LoggerMiddleware already. It is kinda hard to reproduce. I am using over 20 commands. Some are triggered within a command etc.

**Comment by RonRademaker** [comment]
Alright, let me know if you can find out what went wrong. I'll keep the issue open for another week or so.

**Comment by ghost** [comment]
The issue seems to be solved magically. :+1: MongoDB is the solution. Should be used as default. More transparent, more traceable, less errors. 

I am going to close this one if all stays in its current state. 

Thanks for your help @RonRademaker
