### ISSUE TITLE
PHP 7 MongoDB

### ISSUE THREAD

**Issue by ghost** [ConnectHolland/tactician-scheduler-plugin#9]
Hi,

is it possible to use MongoDB instead of Mongo? (http://www.php.net/manual/en/class.mongoclient.php)

**Comment by RonRademaker** [comment]
The `ConnectHolland\Tactician\SchedulerPlugin\Scheduler\MongoScheduler` requires a `MongoCollection` in its constructor. This is a class from MongoDB, if you have the `MongoClient` (from your reference on php.net) in `$client` you can use:

``` php
$scheduler = new ConnectHolland\Tactician\SchedulerPlugin\Scheduler\MongoScheduler($client->selectCollection('scheduled_commands'));
```

Creating a new `Scheduler` isn't too hard either, you only have to implement the `ConnectHolland\Tactician\SchedulerPlugin\Scheduler\SchedulerInterface` which is just two methods. I'll be happy to accept new `Schedulers` into this library or help if you should get stuck somewhere.

**Comment by ghost** [comment]
I totally forgot that I wrote here. pecl mongo is deprecated now, so MongoClient is not accessable anymore. Instead pecl mongodb (https://github.com/mongodb/mongo-php-driver) is used in conjunction with the userland lib (https://github.com/mongodb/mongo-php-library).

I did a new Scheduler implementing your interface and using those two new dependencies 2 days ago. I had to change timestamp values to epoch timestamp because UTCDatetime is currently not working correctly in pecl mongodb.

```
<?php

use ConnectHolland\Tactician\SchedulerPlugin\Command\ScheduledCommandInterface;
use ConnectHolland\Tactician\SchedulerPlugin\Scheduler\SchedulerInterface;
use MongoDB;

class MongoDbScheduler implements SchedulerInterface
{
    /**
     * Collection to store in
     *
     * @var MongoDB\Collection
     */
    private $collection;

    /**
     * Creates a new MongoScheduler
     *
     * @access public
     * @param MongoDB\Collection $collection
     * @return void
     */
    public function __construct(MongoDB\Collection $collection)
    {
        $this->collection = $collection;
    }

    /**
     * Gets the commands that should be executed and removes them from the database
     * @access public
     * @return array
     */
    public function getCommands()
    {
        $time = time();
        $query = ['timestamp' => ['$lt' => $time]];

        $storedCommands = $this->collection->find($query);

        $commands = [];
        foreach ($storedCommands as $storedCommand) {
            $commands[] = unserialize($storedCommand->command);
            $this->collection->deleteOne(['_id' => $storedCommand->_id]);
        }

        return $commands;
    }

    /**
     * Schedules $command to be executed at its set time
     *
     * @param ScheduledCommandInterface $command
     * @param $id
     * @return $id
     */
    public function schedule(ScheduledCommandInterface $command, $id = NULL)
    {
        $date = $command->getTimestamp();

        if (isset($id)) {
            $mongoId = new MongoDB\BSON\ObjectID($id);

            $data = [
                '_id'         => $mongoId,
                'command'     => serialize($command),
                'timestamp'   => $date,
            ];

            $this->collection->updateOne(['_id' => $id], $data);

            return $mongoId->__toString();
        } else {
            $data = [
                'command'     => serialize($command),
                'timestamp'   => $date,
            ];

            $res = $this->collection->insertOne($data);

            return $res->getInsertedId();
        }
    }
}
```

**Comment by RonRademaker** [comment]
Thanks for the update, any chance you can add a namespace, use statements and add tests (basically, meet https://github.com/ConnectHolland/tactician-scheduler-plugin/blob/master/CONTRIBUTING.md) and make a pull request of this? I would like to include it in the package.

**Comment by ghost** [comment]
Yes, I planned to do so. No time before the weekend starts. :-)

**Comment by RonRademaker** [comment]
Great, thx!

**Comment by RonRademaker** [comment]
@varakh just giving you a reminder for this

**Comment by ghost** [comment]
Thanks, sorry for the delay. On thursday I have my last exam. Will do it afterwards. :-)
